language: crystal
services:
  - docker

env:
- MONGODB_HOST=127.0.0.1 MONGODB_PORT=27017 MONGODB_USER=root MONGODB_PASS=example MONGODB_DB_NAME=epidote_test POSTGRES_HOST=localhost POSTGRES_PORT=5432 POSTGRES_USER=postgres POSTGRES_PASS=postgres POSTGRES_DB_NAME=epidote_test MYSQL_HOST=localhost MYSQL_PORT=3306 MYSQL_USER=root MYSQL_PASS=mysql MYSQL_DB_NAME=epidote_test

# Uncomment the following if you'd like Travis to run specs and check code formatting
script:
- docker-compose up --detach
- crystal spec
- crystal tool format --check
