version: "3.8"
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  mongo:
    image: mongo
    ports:
      - 27017:27017
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
