version: "3.8"
services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: epidote_test
    volumes:
      - ./spec/fixtures/db/mysql:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
  cassandra:
    image: bitnami/cassandra:3.11.8-debian-10-r20
    volumes:
      # - ./spec/fixtures/db/cassandra/config.yaml:/bitnami/cassandra/conf/cassandra.yaml:ro
      - ./spec/fixtures/db/cassandra/seed.cql:/docker-entrypoint-initdb.d/seed.cql
    ports:
      - 9042:9042
  test:
    image: kalinon/epidote-test:latest
    build: .
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: "27017"
      MONGODB_USER: root
      MONGODB_PASS: example
      MONGODB_DB_NAME: epidote_test
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
      MYSQL_USER: root
      MYSQL_PASS: mysql
      MYSQL_DB_NAME: epidote_test
      CASSANDRA_HOST: cassandra
      CASSANDRA_DB_NAME: epidote_test
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongo
      - mysql
      - cassandra
    command:
      - /bin/sh
      - -c
      - "shards && crystal spec -v --error-trace"
